apiVersion: v1
items:
# new service for reverse-proxy
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o kompose.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: reverse-proxy
    name: reverse-proxy
  spec:
    ports:
    - name: "80"
      port: 80
      targetPort: 80
    selector:
      io.kompose.service: reverse-proxy
    type: LoadBalancer
  status:
    loadBalancer: {}
# new service for angular
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      io.kompose.service: angular
    name: angular
  spec:
    ports:
    - name: "80"
      port: 80
      targetPort: 80
    selector:
      io.kompose.service: angular
  status:
    loadBalancer: {}
# new service for java
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      io.kompose.service: java
    name: java
  spec:
    ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    selector:
      io.kompose.service: java
  status:
    loadBalancer: {}
# new deployment for angular
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o kompose.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: angular
    name: angular
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: angular
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: kompose convert -f docker-compose.yml -o kompose.yaml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.network/my-thai-star: "true"
          io.kompose.service: angular
      spec:
        containers:
        - image: 140995890056.dkr.ecr.eu-central-1.amazonaws.com/my-thai-star/angular:latest
          imagePullPolicy: IfNotPresent 
          name: mts-angular
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    creationTimestamp: null
    name: my-thai-star
  spec:
    ingress:
    - from:
      - podSelector:
          matchLabels:
            io.kompose.network/my-thai-star: "true"
    podSelector:
      matchLabels:
        io.kompose.network/my-thai-star: "true"
# new deployment for java
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o kompose.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: java
    name: java
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: java
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: kompose convert -f docker-compose.yml -o kompose.yaml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.network/my-thai-star: "true"
          io.kompose.service: java
      spec:
        containers:
        - image: 140995890056.dkr.ecr.eu-central-1.amazonaws.com/my-thai-star/java:latest
          imagePullPolicy: IfNotPresent 
          name: mts-java
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    creationTimestamp: null
    name: my-thai-star
  spec:
    ingress:
    - from:
      - podSelector:
          matchLabels:
            io.kompose.network/my-thai-star: "true"
    podSelector:
      matchLabels:
        io.kompose.network/my-thai-star: "true"
# new deployment for reverse-proxy
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o kompose.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: reverse-proxy
    name: reverse-proxy
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: reverse-proxy
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: kompose convert -f docker-compose.yml -o kompose.yaml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.network/my-thai-star: "true"
          io.kompose.service: reverse-proxy
      spec:
        containers:
        - image: 140995890056.dkr.ecr.eu-central-1.amazonaws.com/my-thai-star/reverse-proxy:latest
          imagePullPolicy: IfNotPresent 
          name: mts-reverse-proxy
          ports:
          - containerPort: 80
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    creationTimestamp: null
    name: my-thai-star
  spec:
    ingress:
    - from:
      - podSelector:
          matchLabels:
            io.kompose.network/my-thai-star: "true"
    podSelector:
      matchLabels:
        io.kompose.network/my-thai-star: "true"
kind: List
metadata: {}

